export const strings = {
  app: {
    name: '৪১ দিনে ধূমপান ত্যাগ',
    tagline: 'ইসলামী মূল্যবোধের সাথে ধূমপান ত্যাগ',
  },
  common: {
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল করুন',
    delete: 'মুছে ফেলুন',
    edit: 'সম্পাদনা করুন',
    confirm: 'নিশ্চিত করুন',
    back: 'ফিরে যান',
    next: 'পরবর্তী',
    done: 'সম্পন্ন',
    loading: 'লোড হচ্ছে...',
    yes: 'হ্যাঁ',
    no: 'না',
  },
  navigation: {
    home: 'হোম',
    daily: 'দৈনিক',
    progress: 'অগ্রগতি',
    journal: 'জার্নাল',
    settings: 'সেটিংস',
  },
  onboarding: {
    welcome: 'আসসালামু আলাইকুম',
    welcomeMessage: 'ধূমপান ত্যাগের এই পবিত্র যাত্রায় স্বাগতম',
    quitDate: 'আপনি কবে ধূমপান ছেড়েছেন?',
    cigarettesPerDay: 'প্রতিদিন কতটি সিগারেট খেতেন?',
    pricePerPack: 'এক প্যাকেটের দাম কত? (টাকা)',
    prayerNotifications: 'নামাজের সময় রিমাইন্ডার চান?',
    letsBegin: 'শুরু করুন',
  },
  home: {
    smokeFree: 'ধূমপান মুক্ত',
    moneySaved: 'সঞ্চিত অর্থ',
    cigarettesAvoided: 'এড়ানো সিগারেট',
    todaysTasks: 'আজকের কাজ',
    sosButton: 'জরুরি সাহায্য',
    dailyAffirmation: 'আজকের অনুপ্রেরণা',
  },
  daily: {
    day: 'দিন',
    tasks: 'কাজসমূহ',
    affirmations: 'অনুপ্রেরণা',
    islamicReminder: 'ইসলামী স্মরণিকা',
    cravingTips: 'ক্রেভিং মোকাবেলার টিপস',
    completed: 'সম্পন্ন',
    markComplete: 'সম্পন্ন চিহ্নিত করুন',
  },
  craving: {
    title: 'ক্রেভিং SOS',
    message: 'আপনি পারবেন! এটি মাত্র কয়েক মিনিট স্থায়ী হবে।',
    breathingExercise: 'শ্বাস-প্রশ্বাসের ব্যায়াম',
    copingStrategies: 'মোকাবেলার কৌশল',
    duas: 'দোয়া',
    dhikr: 'জিকির',
    emergencyContacts: 'জরুরি যোগাযোগ',
    logCraving: 'ক্রেভিং রেকর্ড করুন',
    intensity: 'তীব্রতা',
  },
  journal: {
    title: 'জার্নাল',
    newEntry: 'নতুন এন্ট্রি',
    mood: 'মেজাজ',
    triggers: 'ট্রিগার',
    notes: 'নোট',
    selectMood: 'মেজাজ নির্বাচন করুন',
    selectTriggers: 'ট্রিগার নির্বাচন করুন',
  },
  progress: {
    title: 'অগ্রগতি',
    overview: 'সারসংক্ষেপ',
    healthBenefits: 'স্বাস্থ্য উপকারিতা',
    milestones: 'মাইলস্টোন',
    statistics: 'পরিসংখ্যান',
  },
  settings: {
    title: 'সেটিংস',
    profile: 'প্রোফাইল',
    notifications: 'বিজ্ঞপ্তি',
    appearance: 'চেহারা',
    privacy: 'গোপনীয়তা',
    emergencyContacts: 'জরুরি যোগাযোগ',
    dataManagement: 'ডেটা ব্যবস্থাপনা',
    about: 'সম্পর্কে',
  },
  moods: {
    very_happy: 'খুব খুশি',
    happy: 'খুশি',
    neutral: 'স্বাভাবিক',
    sad: 'দুঃখিত',
    very_sad: 'খুব দুঃখিত',
    anxious: 'উদ্বিগ্ন',
    stressed: 'চাপে',
    confident: 'আত্মবিশ্বাসী',
  },
  triggers: {
    stress: 'মানসিক চাপ',
    social: 'সামাজিক',
    boredom: 'একঘেয়েমি',
    after_meal: 'খাবারের পরে',
    coffee: 'কফি',
    alcohol: 'অ্যালকোহল',
    work: 'কাজ',
    home: 'বাড়ি',
    other: 'অন্যান্য',
  },
  errors: {
    generic: 'কিছু ভুল হয়েছে। আবার চেষ্টা করুন।',
    storage: 'ডেটা সংরক্ষণ করতে সমস্যা হয়েছে।',
    permission: 'এই ফিচার ব্যবহার করতে অনুমতি প্রয়োজন।',
    validation: 'দয়া করে সব তথ্য সঠিকভাবে পূরণ করুন।',
    network: 'ইন্টারনেট সংযোগ নেই।',
  },
};
